# Generated by Django 2.0.7 on 2018-07-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('element_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.IntegerField()),
                ('alert', models.IntegerField()),
                ('element_name', models.CharField(max_length=400)),
                ('unit', models.CharField(max_length=400)),
                ('alias', models.CharField(max_length=400)),
                ('group_name', models.CharField(max_length=400)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('value_number', models.BinaryField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('manager', models.IntegerField()),
                ('user', models.IntegerField()),
                ('base', models.IntegerField()),
                ('text', models.CharField(max_length=400)),
                ('value_string', models.CharField(max_length=400)),
                ('value_timestamp', models.DateTimeField()),
                ('corrvalue_number', models.BinaryField()),
                ('olvalue_number', models.BinaryField()),
                ('corrvalue_string', models.CharField(max_length=400)),
                ('olvalue_string', models.CharField(max_length=400)),
                ('corrvalue_timestamp', models.DateTimeField()),
                ('olvalue_timestamp', models.DateTimeField()),
                ('offvalue_number', models.BinaryField()),
                ('offvalue_string', models.CharField(max_length=400)),
                ('offvalue_timestamp', models.DateTimeField()),
                ('archive', models.IntegerField()),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Elements')),
            ],
        ),
    ]
